-- Tạo bảng Môn Học (MonHoc)
CREATE TABLE IF NOT EXISTS MonHoc (
    MaMH CHAR(10) NOT NULL PRIMARY KEY,
    TenMH VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    SoTinChi TINYINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tạo bảng Nhân Sự (NhanSu)
CREATE TABLE IF NOT EXISTS NhanSu (
    MaNS CHAR(10) NOT NULL PRIMARY KEY,
    HoTen VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    NgaySinh DATE NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    MatKhau VARCHAR(255) NOT NULL,
    Quyen VARCHAR(20) DEFAULT 'staff' -- Bổ sung quyền (admin/staff)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tạo bảng Công Việc (CongViec)
CREATE TABLE IF NOT EXISTS CongViec (
    MaCV INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TenCV VARCHAR(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    MoTa LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    NgayBatDau DATETIME NOT NULL,
    NgayKetThuc DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tạo bảng Thời Khóa Biểu (TKB) - Lịch phân công giảng dạy
CREATE TABLE IF NOT EXISTS TKB (
    MaNS CHAR(10) NOT NULL,
    MaMH CHAR(10) NOT NULL,
    NgayBatDau DATE NOT NULL,
    NgayKetThuc DATE NOT NULL,
    Ca TINYINT NOT NULL,
    Phong VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    Thu TINYINT NOT NULL,
    PRIMARY KEY (MaNS, MaMH),
    FOREIGN KEY (MaNS) REFERENCES NhanSu(MaNS) ON DELETE CASCADE,
    FOREIGN KEY (MaMH) REFERENCES MonHoc(MaMH) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tạo bảng Phân Công Công Việc (PhanCongCongViec)
CREATE TABLE IF NOT EXISTS PhanCongCongViec (
    MaNS CHAR(10) NOT NULL,
    MaCV INT NOT NULL,
    NgayPhanCong DATE NOT NULL,
    PRIMARY KEY (MaNS, MaCV),
    FOREIGN KEY (MaNS) REFERENCES NhanSu(MaNS) ON DELETE CASCADE,
    FOREIGN KEY (MaCV) REFERENCES CongViec(MaCV) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tạo bảng Báo Cáo Tiến Độ (BaoCaoTienDo)
CREATE TABLE IF NOT EXISTS BaoCaoTienDo (
    MaBC INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    MaNS CHAR(10) NOT NULL,
    MaCV INT NOT NULL,
    NoiDungBaoCao LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    NgayGui DATETIME NOT NULL,
    FOREIGN KEY (MaNS, MaCV) REFERENCES PhanCongCongViec(MaNS, MaCV) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
